{{- range $bucket := .Values.buckets }}
{{- if $bucket.pushSecret }}
{{- if $bucket.pushSecret.enabled }}
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: {{ $bucket.name }}-push-secret
  {{- with $bucket.namespace }}
  namespace: {{ . }}
  {{- end }}
  {{- with $bucket.pushSecret.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $bucket.pushSecret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  refreshInterval: {{ $bucket.pushSecret.refreshInterval | default "1h" }}

  selector:
    secret:
      name: {{ $bucket.pushSecret.sourceSecretName | default (printf "%s-bucket-claim" $bucket.name) }}

  secretStoreRefs:
    - name: {{ $bucket.pushSecret.secretStoreName | required (printf "pushSecret.secretStoreName is required for bucket '%s'" $bucket.name) }}
      kind: {{ $bucket.pushSecret.secretStoreKind | default "ClusterSecretStore" }}

  data:
    {{- range $bucket.pushSecret.secretMappings }}
    - match:
        secretKey: {{ .secretKey | required "secretKey is required in pushSecret.secretMappings" }}
        remoteRef:
          remoteKey: {{ .remoteKey | required "remoteKey is required in pushSecret.secretMappings" }}
    {{- end }}
{{- end }}
{{- end }}
{{- end }}
